name: Lint Commit Messages

on:
  push:
    branches:
      - master
      - "hotfix/*"
  pull_request:

jobs:
  commitlint:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
